# Game Constants
TILE_SIZE = 40
GRID_SZE_ROW = 15
GRID_SZE_COL = 15
WIDTH =  600
HEIGHT = 600
FPS = 60
PLAYER_SIZE = 40
EXCLUDED_ROWS = {0, 1, (GRID_SZE_ROW*GRID_SZE_COL//GRID_SZE_COL-2), (GRID_SZE_ROW*GRID_SZE_COL//GRID_SZE_COL-1)}
EXCLUDED_COLS = {0, 1, 2, (GRID_SZE_ROW*GRID_SZE_COL//GRID_SZE_ROW-3), (GRID_SZE_ROW*GRID_SZE_COL//GRID_SZE_ROW-2),
                 (GRID_SZE_ROW*GRID_SZE_COL//GRID_SZE_ROW-1)}
PROTECTED_TILES = {
    (0, 0),  # Player 1 start
    (GRID_SZE_ROW - 1, GRID_SZE_COL - 1)  # Player 2 start
}
